CREATE TABLE [dbo].[RolEmails] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [Rol]              NVARCHAR (255) DEFAULT ('') NOT NULL,
    [Mail]             NVARCHAR (255) DEFAULT ('') NOT NULL,
    [Dato]             NVARCHAR (255) NULL,
    [CreadoPor]        NVARCHAR (255) NULL,
    [CreadoEn]         DATETIME       DEFAULT (getdate()) NOT NULL,
    [ActualizadoPor]   NVARCHAR (255) NULL,
    [ActualizadoEn]    DATETIME       DEFAULT (getdate()) NOT NULL,
    [RegId]            NVARCHAR (255) NULL,
    [RowVersion]       ROWVERSION     NOT NULL,
    [RolEmail_Empresa] INT            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([RegId] ASC),
    CONSTRAINT [RolEmail_Empresa] FOREIGN KEY ([RolEmail_Empresa]) REFERENCES [dbo].[Empresas] ([Id])
);

CREATE TABLE [dbo].[SendEMails] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
    [Fecha]            DATETIME         DEFAULT (getdate()) NOT NULL,
    [Random]           UNIQUEIDENTIFIER NULL,
    [MailFrom]         NVARCHAR (255)   NULL,
    [MailTo]           NVARCHAR (255)   NULL,
    [Subject]          NVARCHAR (255)   NULL,
    [Body]             NVARCHAR (500)   NULL,
    [Attached]         VARBINARY (MAX)  NULL,
    [FileAttached]     NVARCHAR (255)   NULL,
    [Dato]             NVARCHAR (255)   NULL,
    [CreadoPor]        NVARCHAR (255)   NULL,
    [CreadoEn]         DATETIME         DEFAULT (getdate()) NOT NULL,
    [ActualizadoPor]   NVARCHAR (255)   NULL,
    [ActualizadoEn]    DATETIME         NULL,
    [RegId]            NVARCHAR (255)   NULL,
    [RowVersion]       ROWVERSION       NOT NULL,
    [SendMail_Empresa] INT              DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([RegId] ASC),
    CONSTRAINT [SendEMail_Empresa] FOREIGN KEY ([SendMail_Empresa]) REFERENCES [dbo].[Empresas] ([Id])
);

DROP TABLE [dbo].[SoftClientes];
CREATE TABLE [dbo].[SoftClientes] (
    [Id]                       INT             IDENTITY (1, 1) NOT NULL,
    [SoftProductoId]           NVARCHAR (255)  DEFAULT ('') NOT NULL,
    [SoftProductoCodeName]     NVARCHAR (255)  DEFAULT ('') NOT NULL,
    [SoftProductoNombre]       NVARCHAR (255)  DEFAULT ('') NOT NULL,
    [SoftProductoModelo]       NVARCHAR (255)  NULL,
    [SoftProductoVersion]      NVARCHAR (255)  DEFAULT ('') NOT NULL,
    [ClienteId]                NVARCHAR (255)  DEFAULT ('') NOT NULL,
    [ClienteNombre]            NVARCHAR (255)  DEFAULT ('') NOT NULL,
    [NroEmpresas]              INT             DEFAULT ((0)) NOT NULL,
    [NroInstalaciones]         INT             DEFAULT ((0)) NOT NULL,
    [InstalacionesEnEjecucion] INT             DEFAULT ((0)) NOT NULL,
    [SMTP_Enabled]             BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_CajaEnabled]         BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_SupervisorEnabled]   BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_AperturaEnabled]     BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_CierreEnabled]       BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_AnulacionEnabled]    BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_Server]              NVARCHAR (255)  NULL,
    [SMTP_Port]                NVARCHAR (255)  NULL,
    [SMTP_EnableSSL]           BIT             DEFAULT ((0)) NOT NULL,
    [SMTP_DeliveryMethod]      NVARCHAR (255)  NULL,
    [SMTP_UserId]              NVARCHAR (255)  NULL,
    [SMTP_Pwd]                 NVARCHAR (255)  NULL,
    [SMTP_From]                NVARCHAR (255)  NULL,
    [CreadoPor]                NVARCHAR (255)  NULL,
    [CreadoEn]                 DATETIME        NULL,
    [ActualizadoPor]           NVARCHAR (255)  NULL,
    [ActualizadoEn]            DATETIME        NULL,
    [RegId]                    NVARCHAR (255)  NULL,
    [TimeStamp]                VARBINARY (MAX) NULL,
    [RowVersion]               ROWVERSION      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([RegId] ASC)
);